[package]
name = "pogla_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
sdl2 = "0.35.2"
ansi_term = "0.12.1"
log = "0.4.17"
env_logger = "0.10.0"
